name: Deploy Docker Services
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clean up old resources
      run: |
        docker-compose down --volumes --remove-orphans
        docker container prune -f
        docker volume prune -f

    - name: Build and deploy
      run: |
        docker-compose build --parallel
        docker-compose up -d
